// file generated by 'generateRoutes.ts'

import { createRouter } from "radix3";
import TodosPage from "./routes/todos";
import IndexPage from "./routes/index";
import Todos$idPage, { loader as loader$2 } from "./routes/todos/$id";
import _layoutPage, { loader as _layoutPage_loader } from "./routes/_layout";

interface Layout {
  id: string;
  layoutPath: string;
  component?: (props: { children: any }) => any;
  loader?: (...args: any[]) => any | Promise<any>;
}

interface Route {
  id: string;
  routePath: string;
  component?: () => any;
  loader?: (...args: any[]) => any | Promise<any>;
  layouts?: Layout[];
}

interface ErrorRoute {
  id: string;
  routePath: string;
  component: () => any;
}

interface Action {
  id: string;
  actionPath: string;
  functionName: string;
  action: (...args: any[]) => Promise<any>;
}

const router = createRouter<Route>({
  routes: {
    "/todos": {
      id: "/todos",
      component: TodosPage,
      routePath: "todos.tsx",
      loader: undefined,
      layouts: [
        {
          id: "/",
          layoutPath: "_layout.tsx",
          component: _layoutPage,
          loader: _layoutPage_loader,
        },
      ],
    },
    "/": {
      id: "/",
      component: IndexPage,
      routePath: "index.tsx",
      loader: undefined,
      layouts: [
        {
          id: "/",
          layoutPath: "_layout.tsx",
          component: _layoutPage,
          loader: _layoutPage_loader,
        },
      ],
    },
    "/todos/:id": {
      id: "/todos/:id",
      component: Todos$idPage,
      routePath: "todos\\$id.tsx",
      loader: loader$2,
      layouts: [
        {
          id: "/",
          layoutPath: "_layout.tsx",
          component: _layoutPage,
          loader: _layoutPage_loader,
        },
      ],
    },
  },
});

const errorRouter = createRouter<ErrorRoute>({ routes: {} });

const actionRouter = createRouter<Action>({ routes: {} });

export const matchRoute = (pathname: string) => router.lookup(pathname);

export const matchErrorRoute = (pathname: string) =>
  errorRouter.lookup(pathname);

export const matchAction = (id: string) => actionRouter.lookup(id);
