// file generated by 'generateRoutes.ts'

import { createRouter } from "radix3";

interface Route {
  id: string;
  routePath: string;
  component?: () => any;
  loader?: (...args: any[]) => any | Promise<any>;
}

interface ErrorRoute {
  id: string;
  routePath: string;
  component: () => any;
}

interface Action {
  id: string;
  actionPath: string;
  functionName: string;
  action: (...args: any[]) => Promise<any>;
}

const router = createRouter<Route>({ routes: {} });

const errorRouter = createRouter<ErrorRoute>({ routes: {} });

const actionRouter = createRouter<Action>({ routes: {} });

export const matchRoute = (pathname: string) => router.lookup(pathname);

export const matchErrorRoute = (pathname: string) =>
  errorRouter.lookup(pathname);

export const matchAction = (id: string) => actionRouter.lookup(id);
